#!/bin/bash

echo "🌐 Social Media Preview Testing Guide"
echo "====================================="
echo ""
echo "To test social media previews, you need a PUBLIC URL."
echo "Localhost URLs (http://localhost:8087) won't work!"
echo ""
echo "Option 1: Use ngrok (for testing)"
echo "---------------------------------"
echo "1. Start ngrok tunnel:"
echo "   ngrok http 8087"
echo ""
echo "2. Copy the public URL (e.g., https://abc123.ngrok.io)"
echo ""
echo "3. Test with your blog post:"
echo "   https://abc123.ngrok.io/blog/1_million_per_week_with_claude_code"
echo ""
echo "4. Share this PUBLIC URL in your message app"
echo ""
echo "Option 2: Deploy to Production"
echo "------------------------------"
echo "1. Deploy your site to production"
echo ""
echo "2. Test with production URL:"
echo "   https://blockheadconsulting.com/blog/1_million_per_week_with_claude_code"
echo ""
echo "3. Use social media debuggers:"
echo "   - Facebook: https://developers.facebook.com/tools/debug/"
echo "   - Twitter: https://cards-dev.twitter.com/validator"
echo "   - LinkedIn: https://www.linkedin.com/post-inspector/"
echo ""
echo "⚠️  IMPORTANT: Social media previews ONLY work with PUBLIC URLs!"
echo ""
echo "Press Ctrl+C to exit ngrok when done testing."