# name: Test Suite
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# jobs:
#   test-go:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     
#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.24'
#     
#     - name: Install dependencies
#       run: go mod download
#     
#     - name: Run Go tests
#       run: go test -v ./...
#     
#     - name: Run Go race tests
#       run: go test -race -v ./...
# 
#   test-javascript:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     
#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
#     
#     - name: Install dependencies
#       run: npm ci
#     
#     - name: Run JavaScript tests
#       run: npm run test:js
#     
#     - name: Run test coverage
#       run: npm run test:js:coverage
#     
#     - name: Upload coverage reports
#       uses: codecov/codecov-action@v3
#       with:
#         file: ./coverage/lcov.info
# 
#   test-e2e:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v3
#     
#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.24'
#     
#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
#     
#     - name: Install dependencies
#       run: |
#         go mod download
#         npm ci
#         npx playwright install chromium
#     
#     - name: Start server
#       run: |
#         go run main.go &
#         sleep 5
#       env:
#         PORT: 8087
#         CALENDAR_ENABLED: false
#         ENVIRONMENT: test
#     
#     - name: Run E2E tests
#       run: npm run test:e2e
#       env:
#         CI: true